version: '3.3'

services:

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  gretel_ner:
    container_name: gretel_ner
    image: gretelai/ner:latest
    environment:
      - GRETEL_DEV_EP=yes
      - GRETEL_API_KEY=${GRETEL_API_KEY}
    ports:
      - 8000:8000

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.9.2
    environment:
      - xpack.monitoring.enabled=false
    ports:
      - 8080:8080
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
      - gretel_ner

volumes:
  elasticsearch-data:
    driver: local
