apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gretel-ner.fullname" . }}
  labels:
    {{- include "gretel-ner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gretel-ner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gretel-ner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              drop:
                - ALL
          env:
          - name: GRETEL_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-token
                key: token
          - name: GRETEL_DEV_EP
            value: {{ quote .Values.devMode }}
          - name: DETECTION_MODE
            value: {{ quote .Values.detectionMode }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          # Disabled until status goes in
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
